# Manipulating data with the Pandas library
- Import the pandas library.
- Read the file "food_info.csv" in a dataframe called food_info.
- Use the Dataframe.columns attribute followed by the Index.tolist() method to return a list containing all food_info column names.
- Assign the resulting list to the col_names variable and use the print() function to display the column names.
- Finally display the first 3 elements of food_info.

In [3]:
import pandas as pd
food_info = pd.read_csv("food_info.csv")
col_names = food_info.columns.tolist()
print(col_names)

['Energ_Kcal', 'Protein_(g)', 'Lipid_Tot_(g)', 'Ash_(g)', 'Carbohydrt_(g)', 'Fiber_TD_(g)', 'Sugar_Tot_(g)', 'Calcium_(mg)', 'Iron_(mg)', 'Magnesium_(mg)', 'Phosphorus_(mg)', 'Potassium_(mg)', 'Sodium_(mg)', 'Zinc_(mg)', 'Copper_(mg)', 'Manganese_(mg)', 'Selenium_(mcg)', 'Vit_C_(mg)', 'Thiamin_(mg)', 'Riboflavin_(mg)', 'Niacin_(mg)', 'Vit_B6_(mg)', 'Vit_B12_(mcg)', 'Vit_A_IU', 'Vit_A_RAE', 'Vit_E_(mg)', 'Vit_D_mcg', 'Vit_D_IU', 'Vit_K_(mcg)', 'FA_Sat_(g)', 'FA_Mono_(g)', 'FA_Poly_(g)', 'Cholestrl_(mg)']

In [5]:
food_info.iloc[:3,:]

,NDB_No,Shrt_Desc,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),Sugar_Tot_(g),...,Vit_A_IU,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg)
0,1001,BUTTER WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0
1,1002,BUTTER WHIPPED WITH SALT,15.87,717,0.85,81.11,2.11,0.06,0.0,0.06,...,2499.0,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0
2,1003,BUTTER OIL ANHYDROUS,0.24,876,0.28,99.48,0.00,0.00,0.0,0.00,...,3069.0,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0

## Transform a column

- Divide the column "Sodium_(mg)" by 1000 to convert this column to grams and assign the result to the variable sodium_grams.
- Multiply the column "Sugar__Tot_(g)" by 1000 to convert to milligrams and assign the result to the variable sugar_milligrams.

In [19]:
food_info["Sodium_(mg)2"] = food_info["Sodium_(mg)"]/1000
sugar_milligrams = food_info["Sugar_Tot_(g)"]*1000
print(sodium_grams,sugar_milligrams)
#food_info.assign(sodium_grams = food_info["Sodium_(mg)"]/1000)

0       0.643
1       0.659
2       0.002
3       1.146
4       0.560
        ...
8613    4.450
8614    0.667
8615    0.058
8616    0.070
8617    0.068
Name: Sodium_(mg), Length: 8618, dtype: float64 0          60.0
1          60.0
2           0.0
3         500.0
4         510.0
         ...
8613        0.0
8614        0.0
8615    73200.0
8616        0.0
8617        0.0
Name: Sugar_Tot_(g), Length: 8618, dtype: float64

## Mathematical operations between columns

- Divide the column "Protein_(g)" by the column "Water_(g)" and assign the result to the variable grams_of_protein_per_gram_of_water.
- Add the columns "Calcium_(mg)" and "Iron_(mg)" and assign the result to the variable milligrams_of_calcium_and_iron.
- Display the results.

In [13]:
grams_of_protein_per_gram_of_water = food_info["Protein_(g)"]/food_info["Water_(g)"]
grams_of_protein_per_gram_of_water

0       0.053560
1       0.053560
2       1.166667
3       0.504598
4       0.565313
          ...
8613    0.430233
8614    0.292384
8615    0.000000
8616    0.203283
8617    0.252229
Length: 8618, dtype: float64

In [14]:
milligrams_of_calcium_and_iron = food_info["Calcium_(mg)"]+food_info["Iron_(mg)"]
milligrams_of_calcium_and_iron

0        24.02
1        24.16
2         4.00
3       528.31
4       674.43
         ...
8613     67.40
8614     10.58
8615     16.60
8616     13.50
8617    119.40
Length: 8618, dtype: float64

## Create a nutritional index

Score = 2 x (Protein_(g)) - 0.75 x (Lipid_Tot_(g))

- Multiply the column "Protein_(g)" by 2 and assign the result to the variable protein.
- Multiply the column "Lipid_Tot_(g)" by -0.75 and assign the result to the variable fat.
- Add the variables together and assign the result to the variable rating.
- Display the result.

In [17]:
Score = (food_info["Protein_(g)"]*2)-(0.75*food_info["Lipid_Tot_(g)"])
Score

0      -59.1325
1      -59.1325
2      -74.0500
3       21.2450
4       24.2200
         ...
8613    18.1750
8614    40.4500
8615     0.0000
8616    31.1500
8617    39.2250
Length: 8618, dtype: float64

## Standardize columns

- Normalize the values in the column "protein_(g)" and assign the result to the variable normalized_protein.
- Normalize the values in the "Lipid_Tot_(g)" column and assign the result to the normalized_fat variable.

In [26]:
# a = food_info["Protein_(g)"]
# min_max_scaler = preprocessing.MinMaxScaler()
# scaled_array = min_max_scaler.fit_transform(a)
# normalized_protein = pd.DataFrame(scaled_array)
# df_normalized
 
normalized_protein=(food_info["Protein_(g)"]-food_info["Protein_(g)"].mean())/food_info["Protein_(g)"].std()
normalized_protein

0       4.441032
1       4.441032
2       5.598828
3       1.140336
4       1.199581
          ...
8613    0.910920
8614   -0.618102
8615   -0.671044
8616   -0.582807
8617   -0.639531
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

In [27]:
normalized_fat = (food_info["Lipid_Tot_(g)"]-food_info["Lipid_Tot_(g)"].mean())/food_info["Lipid_Tot_(g)"].std()
normalized_fat
#0<a/b<1
#b = max of (a,b)

0       4.441032
1       4.441032
2       5.598828
3       1.140336
4       1.199581
          ...
8613    0.910920
8614   -0.618102
8615   -0.671044
8616   -0.582807
8617   -0.639531
Name: Lipid_Tot_(g), Length: 8618, dtype: float64

## Create a new column

- Assign the normalized column represented by the normalized_protein variable to the new column that will be named "Normalized_Protein" in the food_info dataframe.
- Assign the normalized column represented by the normalized_fat variable to the new column named "Normalized_Fat" in the food_info dataframe.
- Display the first 5 values of the dataframe food_info.

In [29]:
food_info.insert(2, "Normalized_Protein", normalized_protein)

ValueError: cannot insert Normalized_Protein, already exists

In [30]:
food_info

,NDB_No,Shrt_Desc,Normalized_Protein,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),Fiber_TD_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Sodium_(mg)2
0,1001,BUTTER WITH SALT,-1.011689,15.87,717,0.85,81.11,2.11,0.06,0.0,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.643
1,1002,BUTTER WHIPPED WITH SALT,-1.011689,15.87,717,0.85,81.11,2.11,0.06,0.0,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.659
2,1003,BUTTER OIL ANHYDROUS,-1.065714,0.24,876,0.28,99.48,0.00,0.00,0.0,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.002
3,1004,CHEESE BLUE,0.936070,42.41,353,21.40,28.74,5.11,2.34,0.0,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,1.146
4,1005,CHEESE BRICK,1.110468,41.11,371,23.24,29.68,3.18,2.79,0.0,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,0.661204,43.00,305,18.50,25.10,13.40,0.00,0.0,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,4.450
8614,90240,SCALLOP (BAY&SEA) CKD STMD,0.854558,70.25,111,20.54,0.84,2.97,5.41,0.0,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.667
8615,90480,SYRUP CANE,-1.092253,26.00,269,0.00,0.00,0.86,73.14,0.0,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.058
8616,90560,SNAIL RAW,0.433728,79.20,90,16.10,1.40,1.30,2.00,0.0,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.070
8617,93600,TURTLE GREEN RAW,0.784420,78.50,89,19.80,0.50,1.20,0.00,0.0,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.068

In [31]:
food_info.insert(2, "Normalized_Fat", normalized_fat) 
food_info

,NDB_No,Shrt_Desc,Normalized_Fat,Normalized_Protein,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),Carbohydrt_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Sodium_(mg)2
0,1001,BUTTER WITH SALT,4.441032,-1.011689,15.87,717,0.85,81.11,2.11,0.06,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.643
1,1002,BUTTER WHIPPED WITH SALT,4.441032,-1.011689,15.87,717,0.85,81.11,2.11,0.06,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.659
2,1003,BUTTER OIL ANHYDROUS,5.598828,-1.065714,0.24,876,0.28,99.48,0.00,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.002
3,1004,CHEESE BLUE,1.140336,0.936070,42.41,353,21.40,28.74,5.11,2.34,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,1.146
4,1005,CHEESE BRICK,1.199581,1.110468,41.11,371,23.24,29.68,3.18,2.79,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,0.910920,0.661204,43.00,305,18.50,25.10,13.40,0.00,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,4.450
8614,90240,SCALLOP (BAY&SEA) CKD STMD,-0.618102,0.854558,70.25,111,20.54,0.84,2.97,5.41,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.667
8615,90480,SYRUP CANE,-0.671044,-1.092253,26.00,269,0.00,0.00,0.86,73.14,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.058
8616,90560,SNAIL RAW,-0.582807,0.433728,79.20,90,16.10,1.40,1.30,2.00,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.070
8617,93600,TURTLE GREEN RAW,-0.639531,0.784420,78.50,89,19.80,0.50,1.20,0.00,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.068

## Create a column for the standardized nutrition index

Score = 2 x Normalized_Protein - 0.75 x Normalized_Fat

- Use the Normalized_Protein and Normalized_Fat columns with this formula to create a new column named Norm_Nutr_Index.

In [33]:
Score = ((2*food_info['Normalized_Protein'])- (0.75-food_info['Normalized_Fat']))

In [34]:
food_info.insert(2, "Norm_Nutr_Index", Score) 
food_info

,NDB_No,Shrt_Desc,Norm_Nutr_Index,Normalized_Fat,Normalized_Protein,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Sodium_(mg)2
0,1001,BUTTER WITH SALT,1.667655,4.441032,-1.011689,15.87,717,0.85,81.11,2.11,...,684.0,2.32,1.5,60.0,7.0,51.368,21.021,3.043,215.0,0.643
1,1002,BUTTER WHIPPED WITH SALT,1.667655,4.441032,-1.011689,15.87,717,0.85,81.11,2.11,...,684.0,2.32,1.5,60.0,7.0,50.489,23.426,3.012,219.0,0.659
2,1003,BUTTER OIL ANHYDROUS,2.717400,5.598828,-1.065714,0.24,876,0.28,99.48,0.00,...,840.0,2.80,1.8,73.0,8.6,61.924,28.732,3.694,256.0,0.002
3,1004,CHEESE BLUE,2.262476,1.140336,0.936070,42.41,353,21.40,28.74,5.11,...,198.0,0.25,0.5,21.0,2.4,18.669,7.778,0.800,75.0,1.146
4,1005,CHEESE BRICK,2.670517,1.199581,1.110468,41.11,371,23.24,29.68,3.18,...,292.0,0.26,0.5,22.0,2.5,18.764,8.598,0.784,94.0,0.560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8613,83110,MACKEREL SALTED,1.483327,0.910920,0.661204,43.00,305,18.50,25.10,13.40,...,47.0,2.38,25.2,1006.0,7.8,7.148,8.320,6.210,95.0,4.450
8614,90240,SCALLOP (BAY&SEA) CKD STMD,0.341014,-0.618102,0.854558,70.25,111,20.54,0.84,2.97,...,2.0,0.00,0.0,2.0,0.0,0.218,0.082,0.222,41.0,0.667
8615,90480,SYRUP CANE,-3.605550,-0.671044,-1.092253,26.00,269,0.00,0.00,0.86,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.058
8616,90560,SNAIL RAW,-0.465351,-0.582807,0.433728,79.20,90,16.10,1.40,1.30,...,30.0,5.00,0.0,0.0,0.1,0.361,0.259,0.252,50.0,0.070
8617,93600,TURTLE GREEN RAW,0.179308,-0.639531,0.784420,78.50,89,19.80,0.50,1.20,...,30.0,0.50,0.0,0.0,0.1,0.127,0.088,0.170,50.0,0.068

## Sort a DataFrame

- Replace the dataframe food_info by sorting against the Norm_Nutr_Index column in descending order (from largest to smallest)

In [42]:
food_info.sort_values('Norm_Nutr_Index', ascending=False,inplace = True)
food_info

,NDB_No,Shrt_Desc,Norm_Nutr_Index,Normalized_Fat,Normalized_Protein,Water_(g),Energ_Kcal,Protein_(g),Lipid_Tot_(g),Ash_(g),...,Vit_A_RAE,Vit_E_(mg),Vit_D_mcg,Vit_D_IU,Vit_K_(mcg),FA_Sat_(g),FA_Mono_(g),FA_Poly_(g),Cholestrl_(mg),Sodium_(mg)2
4991,16423,SOY PROT ISOLATE K TYPE CRUDE PROT BASIS,13.170046,-0.637640,7.278843,4.98,321,88.32,0.53,3.58,...,0.0,0.00,0.0,0.0,0.0,0.066,0.101,0.258,0.0,0.050
6155,19177,GELATINS DRY PDR UNSWTND,12.627334,-0.664742,7.021038,13.00,335,85.60,0.10,1.30,...,0.0,0.00,0.0,0.0,0.0,0.070,0.060,0.010,0.0,0.196
216,1258,EGG WHITE DRIED STABILIZED GLUCOSE RED,12.467408,-0.640791,6.929100,6.53,362,84.63,0.48,3.63,...,0.0,0.00,0.0,0.0,0.0,0.147,0.173,0.070,20.0,1.014
8152,35055,SEAL BEARDED (OOGRUK) MEAT DRIED (ALASKA NATIVE),12.197304,-0.526083,6.736693,11.60,351,82.60,2.30,3.50,...,393.0,NaN,NaN,NaN,NaN,0.600,1.330,0.370,NaN,NaN
124,1136,EGG WHITE DRIED PDR STABILIZED GLUCOSE RED,12.016951,-0.668523,6.717737,8.54,376,82.40,0.04,4.55,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,1.238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4383,14462,BEVERAGES PROPEL ZERO FRUIT-FLAVORED NON-CARBO...,-3.605550,-0.671044,-1.092253,98.78,5,0.00,0.00,0.08,...,0.0,1.67,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.033
4188,14052,ALCOHOLIC BEV DISTILLED WHISKEY 86 PROOF,-3.605550,-0.671044,-1.092253,63.90,250,0.00,0.00,0.00,...,0.0,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0,0.000
8055,31015,PACE DICED GRN CHILIES,-3.605550,-0.671044,-1.092253,92.30,27,0.00,0.00,1.03,...,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.0,0.333
8054,31014,PACE JALAPENOS NACHO SLICED PEPPERS,-3.605550,-0.671044,-1.092253,91.30,13,0.00,0.00,5.37,...,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.0,1.000
4309,14277,GRAPE DRINK CANNED,-3.605550,-0.671044,-1.092253,84.20,61,0.00,0.00,0.08,...,0.0,0.00,0.0,0.0,0.0,0.000,0.000,0.000,0.0,0.016